### ISSUE TITLE
getting 0 instead of empty field when no data is present.

### ISSUE THREAD

**Issue by rahulamalkar** [dingqiangliu/vertica_pivot#1]
Hi there,
in the use of your function I see that when the data is not present for certain field it is representing that field as empty but I was expecting it to be 0 if empty, tried to go through your code but couldn't figure out what and where to modify so the if data is empty from the query the pivot must display 0 instead of empty field.

**Comment by dingqiangliu** [comment]
@rahulamalkar Do you mean the value of a measure column is NULL?  If so, the current implement logic is right, as you know sum(NULL) should be NULL.
