### ISSUE TITLE
Question: Functionality

### ISSUE THREAD

**Issue by AlmaniaM** [dingqiangliu/vertica_pivot#2]
Hi dingqiangliu,

I was wondering if this function creates decode like statements to pivot on a table or does it pull data from the table and then pivot it? Basically, does this function have the same performance of just making a standard pivot query or is it faster in some way?

Example query:
SELECT GroupColumn1, GroupColumn2
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum1", 0)) AS 'ColumnName1'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum2", 0)) AS 'ColumnName2'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum3", 0)) AS 'ColumnName3'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum1", 0)) AS 'ColumnName1'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2"), 'CompareValue', "SelectColum2", 0)) AS 'ColumnName2'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum3", 0)) AS 'ColumnName3'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum1", 0)) AS 'ColumnName1'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum2", 0)) AS 'ColumnName2'
,sum(DECODE(CAST("PivotCol1" AS VARCHAR) || CAST("PivotCol2" AS VARCHAR), 'CompareValue', "SelectColum3", 0)) AS 'ColumnName3'
 FROM TableName GROUP BY  GroupColumn1, GroupColumn2;

**Comment by dingqiangliu** [comment]
They are Vertica User-Defined Transform Functions,  just batch processing  on each “partition” of table or sub query according OVER clause. Normally it can boost performance multiple or dozens of times against decode functions or case-when expresses.

For details about UDTF, please see: https://www.vertica.com/docs/9.1.x/HTML/index.htm#Authoring/ExtendingVertica/UDx/TypesOfUDxs.htm
