### ISSUE TITLE
Error when building on CentOS 8

### ISSUE THREAD

**Issue by amgiorgi** [dingqiangliu/vertica_pivot#5]
Hi,

when trying to build and install on CentOS I get this error

 Vertica does not build on GCC v8.0 or above

Regards,
Antonio

**Comment by dingqiangliu** [comment]
Right, you need [devtoolset-7 package](https://centos.pkgs.org/7/centos-sclo-rh-testing-x86_64/devtoolset-7-7.0-8.el7.x86_64.rpm.html) for CentOS. Please go [C++SDK](https://www.vertica.com/docs/12.0.x/HTML/Content/Authoring/ExtendingVertica/C++/C++SDK.htm) for more info.
